package dev.lyric.config.test

import com.charleskorn.kaml.PolymorphismStyle
import com.charleskorn.kaml.Yaml
import com.charleskorn.kaml.YamlConfiguration
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.modules.SerializersModule
import kotlinx.serialization.modules.polymorphic
import kotlinx.serialization.modules.subclass
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertIs

	/*
	 * Test Class was generated by ClaudeAI, as I am very lazy
	 */


// --- Test models -------------------------------------------------------------

// Sealed interface, same shape as your MenuAction: mix of zero-property
// classes (the ones that broke YamlKt) and classes with actual fields.
@Serializable
sealed interface Action {

	@Serializable
	@SerialName("next-page")
	class NextPage : Action

	@Serializable
	@SerialName("previous-page")
	class PreviousPage : Action

	@Serializable
	@SerialName("close-menu")
	class CloseMenu : Action

	@Serializable
	@SerialName("pickup-generators")
	data class PickupGenerators(val mode: String) : Action
}

// Unsealed polymorphism example, mirroring kaml's own frontend/backend docs.
// Needs explicit SerializersModule registration - see below.
@Serializable
abstract class Server

@Serializable
@SerialName("frontend")
data class Frontend(val hostname: String) : Server()

@Serializable
@SerialName("backend")
data class Backend(val database: String) : Server()

@Serializable
data class ServerList(val servers: List<Server>)

@Serializable
data class ActionList(val actions: List<Action>)

// --- Test runner ----------------------------------------------------------
// No JUnit/TestNG involved: kotlin.test's assertEquals/assertIs just throw
// AssertionError on failure, same as they would under a framework - this
// just runs them as a plain script and reports pass/fail itself.

private val yaml = Yaml(
	configuration = YamlConfiguration(
		polymorphismStyle = PolymorphismStyle.Property,
		polymorphismPropertyName = "type"
	)
)

// Open/unsealed classes need explicit subtype registration - the compiler
// can't enumerate them automatically like it does for sealed hierarchies,
// since subclasses could live in any module.
private val serversModule = SerializersModule {
	polymorphic(Server::class) {
		subclass(Frontend::class)
		subclass(Backend::class)
	}
}

private val serversYaml = Yaml(
	configuration = YamlConfiguration(
		polymorphismStyle = PolymorphismStyle.Property,
		polymorphismPropertyName = "type"
	),
	serializersModule = serversModule
)

private val tagStyleServersYaml = Yaml(
	configuration = YamlConfiguration(polymorphismStyle = PolymorphismStyle.Tag),
	serializersModule = serversModule
)

fun main() {
	var passed = 0
	var failed = 0

	fun runTest(name: String, block: () -> Unit) {
		try {
			block()
			println("[PASS] $name")
			passed++
		} catch (e: AssertionError) {
			println("[FAIL] $name -> ${e.message}")
			failed++
		} catch (e: Exception) {
			println("[FAIL] $name -> ${e::class.simpleName}: ${e.message}")
			failed++
		}
	}

	runTest("sealed interface decodes zero-property action subtypes") {
		val src = """
            actions:
              - type: 'next-page'
              - type: 'previous-page'
              - type: 'close-menu'
        """.trimIndent()

		val result = yaml.decodeFromString(ActionList.serializer(), src)

		assertEquals(3, result.actions.size)
		assertIs<Action.NextPage>(result.actions[0])
		assertIs<Action.PreviousPage>(result.actions[1])
		assertIs<Action.CloseMenu>(result.actions[2])
	}

	runTest("sealed interface decodes action subtype with a field") {
		val src = """
            actions:
              - type: 'pickup-generators'
                mode: ALL
        """.trimIndent()

		val result = yaml.decodeFromString(ActionList.serializer(), src)
		val action = assertIs<Action.PickupGenerators>(result.actions.single())

		assertEquals("ALL", action.mode)
	}

	runTest("sealed interface decodes mixed zero-property and field-bearing actions") {
		val src = """
            actions:
              - type: 'pickup-generators'
                mode: ALL
              - type: 'close-menu'
        """.trimIndent()

		val result = yaml.decodeFromString(ActionList.serializer(), src)

		assertEquals(2, result.actions.size)
		assertIs<Action.PickupGenerators>(result.actions[0])
		assertIs<Action.CloseMenu>(result.actions[1])
	}

	runTest("unsealed classes decode with property-style polymorphism when registered in a module") {
		val src = """
            servers:
              - type: frontend
                hostname: a.mycompany.com
              - type: backend
                database: db-1
        """.trimIndent()

		val result = serversYaml.decodeFromString(ServerList.serializer(), src)

		assertEquals(2, result.servers.size)
		val frontend = assertIs<Frontend>(result.servers[0])
		val backend = assertIs<Backend>(result.servers[1])
		assertEquals("a.mycompany.com", frontend.hostname)
		assertEquals("db-1", backend.database)
	}

	runTest("unsealed classes decode with tag-style polymorphism when registered in a module") {
		val src = """
            servers:
              - !<frontend>
                hostname: default.mycompany.com
        """.trimIndent()

		val result = tagStyleServersYaml.decodeFromString(ServerList.serializer(), src)

		assertIs<Frontend>(result.servers.single())
	}

	println()
	println("Passed: $passed, Failed: $failed")
}